import Loading from './modules/ui/loading/loading.js';
customElements.define('ourss-loading', Loading.CustomElementConstructor);
import Markdown from './modules/text/markdown/markdown.js';
customElements.define('ourss-markdown', Markdown.CustomElementConstructor);
import Casts from './modules/ui/casts/casts.js';
customElements.define('ourss-casts', Casts.CustomElementConstructor);
import Cast from './modules/ui/cast/cast.js';
customElements.define('ourss-cast', Cast.CustomElementConstructor);
import Auth from './modules/ui/auth/auth.js';
customElements.define('ourss-auth', Auth.CustomElementConstructor);
import Login from './modules/ui/login/login.js';
customElements.define('ourss-login', Login.CustomElementConstructor);
import Player from './modules/ui/player/player.js';
customElements.define('ourss-player', Player.CustomElementConstructor);
import Settings from './modules/ui/settings/settings.js';
customElements.define('ourss-settings', Settings.CustomElementConstructor);
import Playlist from './modules/ui/playlist/playlist.js';
customElements.define('ourss-playlist', Playlist.CustomElementConstructor);
import Button from './modules/ui/button/button.js';
customElements.define('ourss-button', Button.CustomElementConstructor);
import App from './modules/ourss/app/app.js';
customElements.define('ourss-app', App.CustomElementConstructor);
import ImgHeader from './modules/ui/imgHeader/imgHeader.js';
customElements.define('ourss-img-header', ImgHeader.CustomElementConstructor);
import List from './modules/ui/list/list.js';
customElements.define('ourss-list', List.CustomElementConstructor);
import Icon from './modules/ui/icon/icon.js';
customElements.define('ourss-icon', Icon.CustomElementConstructor);